// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package org.hints.blockChain.wallet;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WalletOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wallet.Wallet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string network = 1;</code>
     * @return Whether the network field is set.
     */
    boolean hasNetwork();
    /**
     * <code>optional string network = 1;</code>
     * @return The network.
     */
    String getNetwork();
    /**
     * <code>optional string network = 1;</code>
     * @return The bytes for network.
     */
    com.google.protobuf.ByteString
        getNetworkBytes();

    /**
     * <code>optional bytes keyChainGroup = 2;</code>
     * @return Whether the keyChainGroup field is set.
     */
    boolean hasKeyChainGroup();
    /**
     * <code>optional bytes keyChainGroup = 2;</code>
     * @return The keyChainGroup.
     */
    com.google.protobuf.ByteString getKeyChainGroup();

    /**
     * <code>optional bytes privateKey = 3;</code>
     * @return Whether the privateKey field is set.
     */
    boolean hasPrivateKey();
    /**
     * <code>optional bytes privateKey = 3;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <code>optional bytes publicKey = 4;</code>
     * @return Whether the publicKey field is set.
     */
    boolean hasPublicKey();
    /**
     * <code>optional bytes publicKey = 4;</code>
     * @return The publicKey.
     */
    com.google.protobuf.ByteString getPublicKey();
  }
  /**
   * Protobuf type {@code wallet.Wallet}
   */
  public static final class Wallet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:wallet.Wallet)
      WalletOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Wallet.newBuilder() to construct.
    private Wallet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wallet() {
      network_ = "";
      keyChainGroup_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      publicKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Wallet();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.hints.blockChain.wallet.Protos.internal_static_wallet_Wallet_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.hints.blockChain.wallet.Protos.internal_static_wallet_Wallet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.hints.blockChain.wallet.Protos.Wallet.class, org.hints.blockChain.wallet.Protos.Wallet.Builder.class);
    }

    private int bitField0_;
    public static final int NETWORK_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object network_ = "";
    /**
     * <code>optional string network = 1;</code>
     * @return Whether the network field is set.
     */
    @Override
    public boolean hasNetwork() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string network = 1;</code>
     * @return The network.
     */
    @Override
    public String getNetwork() {
      Object ref = network_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        network_ = s;
        return s;
      }
    }
    /**
     * <code>optional string network = 1;</code>
     * @return The bytes for network.
     */
    @Override
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEYCHAINGROUP_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString keyChainGroup_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes keyChainGroup = 2;</code>
     * @return Whether the keyChainGroup field is set.
     */
    @Override
    public boolean hasKeyChainGroup() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes keyChainGroup = 2;</code>
     * @return The keyChainGroup.
     */
    @Override
    public com.google.protobuf.ByteString getKeyChainGroup() {
      return keyChainGroup_;
    }

    public static final int PRIVATEKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes privateKey = 3;</code>
     * @return Whether the privateKey field is set.
     */
    @Override
    public boolean hasPrivateKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes privateKey = 3;</code>
     * @return The privateKey.
     */
    @Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes publicKey = 4;</code>
     * @return Whether the publicKey field is set.
     */
    @Override
    public boolean hasPublicKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes publicKey = 4;</code>
     * @return The publicKey.
     */
    @Override
    public com.google.protobuf.ByteString getPublicKey() {
      return publicKey_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, network_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, keyChainGroup_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, privateKey_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, publicKey_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, network_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, keyChainGroup_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, privateKey_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, publicKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.hints.blockChain.wallet.Protos.Wallet)) {
        return super.equals(obj);
      }
      org.hints.blockChain.wallet.Protos.Wallet other = (org.hints.blockChain.wallet.Protos.Wallet) obj;

      if (hasNetwork() != other.hasNetwork()) return false;
      if (hasNetwork()) {
        if (!getNetwork()
            .equals(other.getNetwork())) return false;
      }
      if (hasKeyChainGroup() != other.hasKeyChainGroup()) return false;
      if (hasKeyChainGroup()) {
        if (!getKeyChainGroup()
            .equals(other.getKeyChainGroup())) return false;
      }
      if (hasPrivateKey() != other.hasPrivateKey()) return false;
      if (hasPrivateKey()) {
        if (!getPrivateKey()
            .equals(other.getPrivateKey())) return false;
      }
      if (hasPublicKey() != other.hasPublicKey()) return false;
      if (hasPublicKey()) {
        if (!getPublicKey()
            .equals(other.getPublicKey())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNetwork()) {
        hash = (37 * hash) + NETWORK_FIELD_NUMBER;
        hash = (53 * hash) + getNetwork().hashCode();
      }
      if (hasKeyChainGroup()) {
        hash = (37 * hash) + KEYCHAINGROUP_FIELD_NUMBER;
        hash = (53 * hash) + getKeyChainGroup().hashCode();
      }
      if (hasPrivateKey()) {
        hash = (37 * hash) + PRIVATEKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPrivateKey().hashCode();
      }
      if (hasPublicKey()) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKey().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.hints.blockChain.wallet.Protos.Wallet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.hints.blockChain.wallet.Protos.Wallet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.hints.blockChain.wallet.Protos.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.hints.blockChain.wallet.Protos.Wallet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code wallet.Wallet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:wallet.Wallet)
        org.hints.blockChain.wallet.Protos.WalletOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.hints.blockChain.wallet.Protos.internal_static_wallet_Wallet_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.hints.blockChain.wallet.Protos.internal_static_wallet_Wallet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.hints.blockChain.wallet.Protos.Wallet.class, org.hints.blockChain.wallet.Protos.Wallet.Builder.class);
      }

      // Construct using org.hints.blockChain.wallet.Protos.Wallet.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        network_ = "";
        keyChainGroup_ = com.google.protobuf.ByteString.EMPTY;
        privateKey_ = com.google.protobuf.ByteString.EMPTY;
        publicKey_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.hints.blockChain.wallet.Protos.internal_static_wallet_Wallet_descriptor;
      }

      @Override
      public org.hints.blockChain.wallet.Protos.Wallet getDefaultInstanceForType() {
        return org.hints.blockChain.wallet.Protos.Wallet.getDefaultInstance();
      }

      @Override
      public org.hints.blockChain.wallet.Protos.Wallet build() {
        org.hints.blockChain.wallet.Protos.Wallet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public org.hints.blockChain.wallet.Protos.Wallet buildPartial() {
        org.hints.blockChain.wallet.Protos.Wallet result = new org.hints.blockChain.wallet.Protos.Wallet(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.hints.blockChain.wallet.Protos.Wallet result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.network_ = network_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.keyChainGroup_ = keyChainGroup_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.privateKey_ = privateKey_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.publicKey_ = publicKey_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.hints.blockChain.wallet.Protos.Wallet) {
          return mergeFrom((org.hints.blockChain.wallet.Protos.Wallet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.hints.blockChain.wallet.Protos.Wallet other) {
        if (other == org.hints.blockChain.wallet.Protos.Wallet.getDefaultInstance()) return this;
        if (other.hasNetwork()) {
          network_ = other.network_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasKeyChainGroup()) {
          setKeyChainGroup(other.getKeyChainGroup());
        }
        if (other.hasPrivateKey()) {
          setPrivateKey(other.getPrivateKey());
        }
        if (other.hasPublicKey()) {
          setPublicKey(other.getPublicKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                network_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                keyChainGroup_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                privateKey_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                publicKey_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object network_ = "";
      /**
       * <code>optional string network = 1;</code>
       * @return Whether the network field is set.
       */
      public boolean hasNetwork() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string network = 1;</code>
       * @return The network.
       */
      public String getNetwork() {
        Object ref = network_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          network_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string network = 1;</code>
       * @return The bytes for network.
       */
      public com.google.protobuf.ByteString
          getNetworkBytes() {
        Object ref = network_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          network_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string network = 1;</code>
       * @param value The network to set.
       * @return This builder for chaining.
       */
      public Builder setNetwork(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        network_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string network = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetwork() {
        network_ = getDefaultInstance().getNetwork();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string network = 1;</code>
       * @param value The bytes for network to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        network_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString keyChainGroup_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes keyChainGroup = 2;</code>
       * @return Whether the keyChainGroup field is set.
       */
      @Override
      public boolean hasKeyChainGroup() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes keyChainGroup = 2;</code>
       * @return The keyChainGroup.
       */
      @Override
      public com.google.protobuf.ByteString getKeyChainGroup() {
        return keyChainGroup_;
      }
      /**
       * <code>optional bytes keyChainGroup = 2;</code>
       * @param value The keyChainGroup to set.
       * @return This builder for chaining.
       */
      public Builder setKeyChainGroup(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        keyChainGroup_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes keyChainGroup = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyChainGroup() {
        bitField0_ = (bitField0_ & ~0x00000002);
        keyChainGroup_ = getDefaultInstance().getKeyChainGroup();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString privateKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes privateKey = 3;</code>
       * @return Whether the privateKey field is set.
       */
      @Override
      public boolean hasPrivateKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes privateKey = 3;</code>
       * @return The privateKey.
       */
      @Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return privateKey_;
      }
      /**
       * <code>optional bytes privateKey = 3;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        privateKey_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes privateKey = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString publicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes publicKey = 4;</code>
       * @return Whether the publicKey field is set.
       */
      @Override
      public boolean hasPublicKey() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes publicKey = 4;</code>
       * @return The publicKey.
       */
      @Override
      public com.google.protobuf.ByteString getPublicKey() {
        return publicKey_;
      }
      /**
       * <code>optional bytes publicKey = 4;</code>
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        publicKey_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes publicKey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        publicKey_ = getDefaultInstance().getPublicKey();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:wallet.Wallet)
    }

    // @@protoc_insertion_point(class_scope:wallet.Wallet)
    private static final org.hints.blockChain.wallet.Protos.Wallet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.hints.blockChain.wallet.Protos.Wallet();
    }

    public static org.hints.blockChain.wallet.Protos.Wallet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wallet>
        PARSER = new com.google.protobuf.AbstractParser<Wallet>() {
      @Override
      public Wallet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Wallet> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Wallet> getParserForType() {
      return PARSER;
    }

    @Override
    public org.hints.blockChain.wallet.Protos.Wallet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wallet_Wallet_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wallet_Wallet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014wallet.proto\022\006wallet\"\246\001\n\006Wallet\022\024\n\007net" +
      "work\030\001 \001(\tH\000\210\001\001\022\032\n\rkeyChainGroup\030\002 \001(\014H\001" +
      "\210\001\001\022\027\n\nprivateKey\030\003 \001(\014H\002\210\001\001\022\026\n\tpublicKe" +
      "y\030\004 \001(\014H\003\210\001\001B\n\n\010_networkB\020\n\016_keyChainGro" +
      "upB\r\n\013_privateKeyB\014\n\n_publicKeyB%\n\033org.h" +
      "ints.blockChain.walletB\006Protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wallet_Wallet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wallet_Wallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wallet_Wallet_descriptor,
        new String[] { "Network", "KeyChainGroup", "PrivateKey", "PublicKey", "Network", "KeyChainGroup", "PrivateKey", "PublicKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
